timeout: 1
retry-timeout: 2
max-page-number: 1
debug: False
page-template:
    - url: 'https://www.emag.ro/tablete/p{page}/c'
      filters:
          max-price: 3000
          min-price: 1000
          brands:
              - 'apple'
              - 'samsung'
          discount: 10
