timeout: 1
retry-timeout: 1
max-page-number: 100
debug: True
sleep-between-categories: 2
sleep-flexibility: 3
fallback-on-proxies: False
page-template:
    - url: 'https://www.flanco.ro/telefoane-tablete/smartphone/p/{page}.html'
      filters:
          ""
    - url: 'https://www.flanco.ro/telefoane-tablete/smartwatch-si-smartband/smartwatch/p/{page}.html'
      filters:
          ""
